# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

dist: xenial

os: linux

git:
  depth: false

addons:
  sonarcloud:
    organization: dmbenedetti # the key of the org you chose at step #3
    token: ${SONAR_TOKEN}

# Definir o Deploy no Heroku
jobs:
  include:
    - stage: sonarqube
      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask flask-wtf coverage
      script:
        - python -m unittest -v test || travis_terminate 1;
        - coverage run test.py || travis_terminate 1;
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;
        - sonar-scanner || travis_terminate 1;
        #- sonar-scanner -Dsonar.projectKey=dmbenedetti_devopslab || travis_terminate 1;

    - stage: deploy stage
      script: skip
      deploy:
        strategy: api
        provider: heroku
        api_key: $HEROKU_API_KEY
        edge: true 
        app: devopslab-dmbenedetti
        on:
            branch: main
    - stage: test staging
      script: curl https://devopslab-dmbenedetti.herokuapp.com/ || travis_terminate 1;
    - stage: depoy prod
      script: skip
      deploy:
        provider: gae
        keyfile: ../lab-devops-cloud-314122-e13635f3da2e.json
        project: lab-devops-cloud-314122
        on:
            branch: main
    - stage: test prod
      script: curl https://lab-devops-cloud-314122.uc.r.appspot.com/ || travis_terminate 1;

before_install:
- openssl aes-256-cbc -K $encrypted_92144ba6f70c_key -iv $encrypted_92144ba6f70c_iv 
  -in lab-devops-cloud-314122-e13635f3da2e.json.enc -out ../lab-devops-cloud-314122-e13635f3da2e.json
  -d
