# Linguagem Utilizada para Desenvolver a Aplicação
language: python


# Versão que a aplicação suporta.
python:
  - "3.7.9"

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install flask

# Defini o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - python -m unittest -v test

# Definir o Deploy no Heroku
deploy:
  strategy: api
  - provider: heroku
    api_key: 0658147b-b507-426e-9861-64d051736897
    edge: true 
    app: devopslab-dmbenedetti
    on:
        branch: main
  - provider: gae
    keyfile: ../lab-devops-cloud-314122-e13635f3da2e.json
    project: lab-devops-cloud-314122
    on:
        branch: main
        
dist: xenial

os: linux

#before_install:
#- openssl aes-256-cbc -K $encrypted_92144ba6f70c_key -iv $encrypted_92144ba6f70c_iv 
#  -in lab-devops-cloud-314122-e13635f3da2e.json.enc -out ../lab-devops-cloud-314122-e13635f3da2e.json
#  -d

